# Hard requirements for running tests
# NOTE: Basemap is broken as of matplotlib >=3.3 so for documentation
# use 3.2.1. Probably lots of basemap holdouts for next ~5 years.
# NOTE: PyQt5 is needed by pyplot, RTD server *happens* to already have it
# but creating local environment will fail.
name: proplot-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - xarray
  - pandas
  - matplotlib==3.2.1
  - cartopy
  - basemap
  - pandoc
  - ipykernel
  - pip
  - setuptools
  - wheel
  - setuptools_scm
  - setuptools_scm_git_archive
  - pip:
    - ..
    - flake8
    - isort==4.3.21
    - doc8
    - pytest
    - pytest-sugar
    - sphinx>=3.0
    - sphinx-copybutton
    - sphinx_rtd_theme==0.4.3
    - jupytext
    - nbsphinx
    - git+https://github.com/lukelbd/sphinx-automodapi@v0.8.proplot-mods
    - git+https://github.com/pypa/build.git
    - pyqt5
